version: "3"
services:
  db:
    image: postgres:13.1-alpine
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_device
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"  # Exposes PostgreSQL
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"  # Exposes pgAdmin on port 5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: always

volumes:
  pgdata:
  pgadmin_data:
